export const users = [
  { id: 1, firstname: "John", lastname: "Doe", age: 28, city: "New York" },
  { id: 2, firstname: "Jane", lastname: "Smith", age: 34, city: "Los Angeles" },
  {
    id: 3,
    firstname: "Michael",
    lastname: "Johnson",
    age: 41,
    city: "Chicago",
  },
  { id: 4, firstname: "Emily", lastname: "Davis", age: 25, city: "Houston" },
  { id: 5, firstname: "Daniel", lastname: "Brown", age: 37, city: "Phoenix" },
  {
    id: 6,
    firstname: "Olivia",
    lastname: "Wilson",
    age: 29,
    city: "Philadelphia",
  },
  {
    id: 7,
    firstname: "James",
    lastname: "Taylor",
    age: 45,
    city: "San Antonio",
  },
  {
    id: 8,
    firstname: "Sophia",
    lastname: "Anderson",
    age: 31,
    city: "San Diego",
  },
  { id: 9, firstname: "William", lastname: "Thomas", age: 52, city: "Dallas" },
  { id: 10, firstname: "Ava", lastname: "Moore", age: 26, city: "San Jose" },

  {
    id: 11,
    firstname: "Benjamin",
    lastname: "Martin",
    age: 38,
    city: "Austin",
  },
  {
    id: 12,
    firstname: "Isabella",
    lastname: "Jackson",
    age: 33,
    city: "Seattle",
  },
  { id: 13, firstname: "Lucas", lastname: "White", age: 27, city: "Denver" },
  { id: 14, firstname: "Mia", lastname: "Harris", age: 35, city: "Boston" },
  { id: 15, firstname: "Henry", lastname: "Clark", age: 44, city: "Atlanta" },
  { id: 16, firstname: "Charlotte", lastname: "Lewis", age: 24, city: "Miami" },
  { id: 17, firstname: "Alexander", lastname: "Lee", age: 39, city: "Orlando" },
  { id: 18, firstname: "Amelia", lastname: "Walker", age: 28, city: "Tampa" },
  { id: 19, firstname: "Ethan", lastname: "Hall", age: 32, city: "Nashville" },
  { id: 20, firstname: "Harper", lastname: "Allen", age: 29, city: "Portland" },

  { id: 21, firstname: "Noah", lastname: "Young", age: 36, city: "Salem" },
  { id: 22, firstname: "Evelyn", lastname: "King", age: 41, city: "Las Vegas" },
  { id: 23, firstname: "Logan", lastname: "Wright", age: 27, city: "Reno" },
  { id: 24, firstname: "Abigail", lastname: "Scott", age: 34, city: "Boise" },
  { id: 25, firstname: "Mason", lastname: "Green", age: 46, city: "Helena" },
  { id: 26, firstname: "Ella", lastname: "Adams", age: 23, city: "Madison" },
  {
    id: 27,
    firstname: "Elijah",
    lastname: "Baker",
    age: 31,
    city: "Milwaukee",
  },
  {
    id: 28,
    firstname: "Lily",
    lastname: "Gonzalez",
    age: 37,
    city: "Santa Fe",
  },
  { id: 29, firstname: "Oliver", lastname: "Nelson", age: 42, city: "Boulder" },
  {
    id: 30,
    firstname: "Grace",
    lastname: "Carter",
    age: 28,
    city: "Fort Collins",
  },

  { id: 31, firstname: "Jacob", lastname: "Mitchell", age: 35, city: "Omaha" },
  { id: 32, firstname: "Chloe", lastname: "Perez", age: 26, city: "Lincoln" },
  {
    id: 33,
    firstname: "Samuel",
    lastname: "Roberts",
    age: 49,
    city: "Des Moines",
  },
  {
    id: 34,
    firstname: "Victoria",
    lastname: "Turner",
    age: 33,
    city: "Cedar Rapids",
  },
  { id: 35, firstname: "David", lastname: "Phillips", age: 40, city: "Topeka" },
  {
    id: 36,
    firstname: "Scarlett",
    lastname: "Campbell",
    age: 22,
    city: "Lawrence",
  },
  { id: 37, firstname: "Joseph", lastname: "Parker", age: 55, city: "Wichita" },
  { id: 38, firstname: "Hannah", lastname: "Evans", age: 30, city: "Columbia" },
  {
    id: 39,
    firstname: "Andrew",
    lastname: "Edwards",
    age: 34,
    city: "Jefferson City",
  },
  {
    id: 40,
    firstname: "Zoey",
    lastname: "Collins",
    age: 27,
    city: "Springfield",
  },

  {
    id: 41,
    firstname: "Christopher",
    lastname: "Stewart",
    age: 43,
    city: "Little Rock",
  },
  {
    id: 42,
    firstname: "Penelope",
    lastname: "Sanchez",
    age: 36,
    city: "Fayetteville",
  },
  {
    id: 43,
    firstname: "Joshua",
    lastname: "Morris",
    age: 29,
    city: "Bentonville",
  },
  {
    id: 44,
    firstname: "Riley",
    lastname: "Rogers",
    age: 32,
    city: "Jonesboro",
  },
  { id: 45, firstname: "Ryan", lastname: "Reed", age: 47, city: "Jackson" },
  { id: 46, firstname: "Aria", lastname: "Cook", age: 25, city: "Gulfport" },
  { id: 47, firstname: "Nathan", lastname: "Morgan", age: 38, city: "Biloxi" },
  {
    id: 48,
    firstname: "Layla",
    lastname: "Bell",
    age: 34,
    city: "Hattiesburg",
  },
  {
    id: 49,
    firstname: "Christian",
    lastname: "Murphy",
    age: 41,
    city: "Tupelo",
  },
  { id: 50, firstname: "Nora", lastname: "Bailey", age: 28, city: "Oxford" },

  { id: 51, firstname: "Aaron", lastname: "Rivera", age: 36, city: "Memphis" },
  { id: 52, firstname: "Lucy", lastname: "Cooper", age: 31, city: "Knoxville" },
  {
    id: 53,
    firstname: "Isaac",
    lastname: "Richardson",
    age: 45,
    city: "Chattanooga",
  },
  { id: 54, firstname: "Anna", lastname: "Cox", age: 24, city: "Murfreesboro" },
  {
    id: 55,
    firstname: "Jonathan",
    lastname: "Howard",
    age: 39,
    city: "Franklin",
  },
];
